# Generated by Django 4.1.7 on 2023-03-23 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_room_online_user_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roommember',
            old_name='channels_names',
            new_name='channel_names',
        ),
    ]
